const palette = {
  kiup: '#2ecc71',
  white: '#ffffff',
  dark_white: '#FAFAFC',
  red: '#F24453',
  protein: '#FFE178',
  sodium: '#EFA2F5',
  phosphorus: '#99FF99',
  potassium: '#EF5C5C',
  dark_emphasis_text: 'rgba(0, 0, 0, 0.87)',
  medium_emphasis_text: 'rgba(0, 0, 0, 0.67)',
  disable_text: 'rgba(0, 0, 0, 0.38)',
  grey_70: 'rgba(0,0,0,0.7)',
  grey_60: 'rgba(0,0,0,0.6)',
  grey_40: 'rgba(0,0,0,0.4)',
  grey_30: 'rgba(0,0,0,0.3)',
  dark_grey: 'rgba(31, 51, 61, 0.3)',
  ios_grey: '#d0d2db',
  ios_white: '#f0f0f3',
  grey_disable: '#cccccc',
};

const colors = {
  primary: palette.kiup,
  secondary: palette.white,
  ternary: palette.dark_white,
  disable: palette.grey_disable,
  error: palette.red,
  protein: palette.protein,
  sodium: palette.sodium,
  phosphorus: palette.phosphorus,
  potassium: palette.potassium,
  very_light_grey: palette.grey_30,
  separator: palette.grey_30,
  light_grey: palette.grey_40,
  grey: palette.grey_60,
  dark_grey: palette.grey_70,
  dark_white: palette.dark_white,
  ios_grey: palette.ios_grey,
  ios_white: palette.ios_white,
  dark_text: palette.dark_emphasis_text,
  medium_text: palette.medium_emphasis_text,
  disable_text: palette.disable_text,
};

export default colors;
